version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./frontend/build:/var/www/frontend/build
    ports:
      - 80:80

  react:
    build:
      context: ./frontend
      dockerfile: react.dockerfile
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend
    ports:
      - 3000:3000
